spring:
  application:
    name: orders-service
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/ms_orders
    username: ivra
    password: Test123
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/microservices-realm/protocol/openid-connect/certs

  #Eureka client
  eureka:
    client:
      service-url:
        default-zone: http://eureka:password@localhost:8761/eureka
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

server:
  port: 0

###Actuator
management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator/orders
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enable: true