spring:
  application:
    name: discovery-service
  security:
    user:
      name: eureka
      password: password

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#Log
logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
